image: "node:latest"

stages:
- pages

pages:
  stage: pages
  script:
  - git clone https://github.com/hakimel/reveal.js.git
  - mkdir public
  - mv reveal.js/{css,js,lib,plugin} public
  - mv ressources index.html public/
  - cd public
  artifacts:
    paths:
      - public/
  only:
    - master


