image: "bravissimolabs/alpine-git:latest"

stages:
- pages

pages:
  stage: pages
  script:
  - git clone https://github.com/hakimel/reveal.js.git
  - mkdir -p public/reveal.js
  - mv reveal.js/{css,js,lib,plugin} public/reveal.js
  - mv ressources index.html public/
  - cd public
  artifacts:
    paths:
      - public/
  only:
    - master


